//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackLite.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.AccountCodes = new HashSet<AccountCode>();
        }
    
        public int AccountId { get; set; }
        public int ClientId { get; set; }
        public string Identifier { get; set; }
        public int PlatformId { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<AccountCode> AccountCodes { get; set; }
    }
}
