//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackLite.Data.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BackLiteEntities : DbContext
    {
        public BackLiteEntities()
            : base("name=BackLiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccountCode> AccountCodes { get; set; }
        public DbSet<Account> Accounts { get; set; }
    
        public virtual ObjectResult<Platforms_Tree_Result> Platforms_Tree()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Platforms_Tree_Result>("Platforms_Tree");
        }
    }
}
